#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import shutil
import stat
import tomllib
from pathlib import Path


LAB_ROOT = Path(__file__).resolve().parents[1]
SOURCE_CODEX = Path(os.environ.get("CODEX_SOURCE_HOME", Path.home() / ".codex")).expanduser()
TARGET_CODEX = LAB_ROOT / "runtime" / "codex-home" / ".codex"


def toml_scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ", ".join(toml_scalar(item) for item in value) + "]"
    raise TypeError(f"unsupported TOML value type: {type(value).__name__}")


def write_minimal_config(source: Path, target: Path) -> None:
    data = tomllib.loads(source.read_text())
    base_url_override = os.environ.get("CODEX_LAB_BASE_URL")
    top_level_keys = ("model_provider", "model", "model_reasoning_effort")
    provider_keys = data.get("model_providers", {})

    lines: list[str] = [
        f"# Generated by {Path(__file__).resolve()}",
        "# Minimal config for the transparent mitmproxy Codex lab.",
        "",
    ]

    for key in top_level_keys:
        if key in data:
            lines.append(f"{key} = {toml_scalar(data[key])}")

    if provider_keys:
        lines.append("")
        lines.append("[model_providers]")
        for provider_name, provider in provider_keys.items():
            if not isinstance(provider, dict):
                continue
            lines.append("")
            lines.append(f"[model_providers.{provider_name}]")
            for key, value in provider.items():
                if key == "base_url" and base_url_override:
                    value = base_url_override
                if isinstance(value, dict):
                    continue
                lines.append(f"{key} = {toml_scalar(value)}")

    lines.append("")
    target.write_text("\n".join(lines))
    target.chmod(0o600)


def find_auth_file(source: Path) -> Path:
    direct = source / "auth.json"
    if direct.exists():
        return direct.resolve()

    auths = source / "auths"
    if auths.is_dir():
        candidates = sorted(auths.glob("*.json"), key=lambda path: path.stat().st_mtime, reverse=True)
        if candidates:
            return candidates[0].resolve()

    raise SystemExit(f"missing Codex auth file under {source}")


def main() -> None:
    TARGET_CODEX.mkdir(parents=True, exist_ok=True)

    source_config = SOURCE_CODEX / "config.toml"
    source_auth = find_auth_file(SOURCE_CODEX)
    target_config = TARGET_CODEX / "config.toml"
    target_auth = TARGET_CODEX / "auth.json"

    if not source_config.exists():
        raise SystemExit(f"missing source config: {source_config}")

    write_minimal_config(source_config, target_config)
    shutil.copy2(source_auth, target_auth)
    target_auth.chmod(stat.S_IRUSR | stat.S_IWUSR)

    print(f"wrote {target_config}")
    print(f"copied {source_auth} -> {target_auth}")


if __name__ == "__main__":
    main()
